#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Get application name
application=`getApplication`
#blockMesh
#setFields
#decomposePar
./meshCreate
$application > log &
#mpirun -np 2 $application -parallel > log &
#reconstructPar

#------------------------------------------------------------------------------
