#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Get application name
application=`getApplication`
blockMesh
setFields
#decomposePar
$application > log &
#mpirun -np 4 $application -parallel > log &
#reconstructPar

#------------------------------------------------------------------------------
