#!/bin/bash

# shortcut for starting ipython, here with paraview capabilites

# JJS 2010, 2011, 2012, 2018

# set the ETS toolkit to use
export ETS_TOOLKIT=qt4

# path for paraview's python and vtk installed files -- I shouldn't need the .../vtk/ folder, but adding it seems to solve the problem, JJS 2/8/18
export PYTHONPATH="/usr/local/lib/paraview-5.4/site-packages/vtk/:/usr/local/lib/paraview-5.4/site-packages/:/usr/local/lib/paraview-5.4/:$PYTHONPATH"
#export PYTHONPATH="/usr/local/lib/paraview-5.4/site-packages/:/usr/local/lib/paraview-5.4/:$PYTHONPATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/paraview-5.4/"
# hack to put import system paths in front of paraview paths to workaround bug with pygments.lexer and jupyter, JJS 11/10/16
export PYTHONPATH="/usr/lib/python3/dist-packages/:$PYTHONPATH"

ipython3
