#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cp -r oldC/dynamicCode ./
cp 0/alpha.particles.orig 0/alpha.particles
cp 0/alpha.air.orig 0/alpha.air
rm -r VTK*
rm log*
rm core*
rm *~
rm */*~
#cp -r ./meshRun/. ./
#------------------------------------------------------------------------------
